version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: email_service_nginx
    ports:
      - "8888:80"
    volumes:
      - .docker/config/nginx.conf:/etc/nginx/nginx.conf:ro

  app:
    image: email_service_app
    container_name: email_service_app
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    ports:
      - "9000"
    volumes:
      - .docker/config/php.ini:/usr/local/etc/php/php.ini

  db:
    image: postgres:alpine
    container_name: email_service_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 65432:5432
    volumes: 
      - postgresql-data:/var/lib/postgresql/data
      - .docker/postgresql:/docker-entrypoint-initdb.d

  worker:
    image: email_service_app
    command: "php /var/www/html/worker.php"
    restart: on-failure
    depends_on:
      - db
      - rabbitmq
    links: 
      - db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      
volumes:
  postgresql-data:
    driver: local
  rabbitmq-data: